CREATE DATABASE rabata1;

CREATE TABLE IF NOT EXISTS public.users (
	user_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_name varchar NOT NULL,
	email varchar NOT NULL,
	validts timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON public.users USING btree (email);

INSERT INTO public.users (user_name,email,validts) VALUES
     ('user4','email1@sample.com','2022-08-15 07:29:57.169'),
     ('user7','email1@sample.com','2022-08-15 07:29:57.169'),
     ('user6','email1@sample.com','2022-08-15 07:29:57.169'),
     ('user5','email1@sample.com','2022-08-15 07:29:57.169'),
     ('user3','email1@sample.com','2022-08-15 07:29:57.169'),
     ('user2','email1@sample.com','2022-08-15 07:29:57.169'),
	 ('user1','email1@sample.com','2023-08-15 07:29:57.169');


CREATE TABLE IF NOT EXISTS public.emails (
	email varchar NULL,
	checked int4 NULL DEFAULT 0,
	"valid" int4 NULL DEFAULT 0,
	confirmed int4 NULL DEFAULT 0
);
create UNIQUE INDEX IF NOT EXISTS emails_email_idx ON public.emails USING btree (email);

INSERT INTO public.emails (email,checked,"valid",confirmed) VALUES
	 ('email4@sample.com',0,0,0),
	 ('email7@sample.com',0,0,0),
	 ('email6@sample.com',0,0,0),
	 ('email5@sample.com',0,0,0),
	 ('email3@sample.com',0,0,0),
	 ('email2@sample.com',0,0,0),
	 ('email1@sample.com',1,1,1);
